apiVersion: v1
kind: Config
clusters:
  - name: authorize-service
    cluster:
      certificate-authority: /files/ca.crt
      server: http://192.168.5.46:8081/authorize

users:
  - name: authorize-api-server
    user:
      # This will come in the request header(Authorization) of above URL.
      # Can be used to validate if the request is coming from configured cluster
      token: test-token

current-context: webhook
contexts:
- context:
    cluster: authorize-service
    user: authorize-api-server
  name: webhook