apiVersion: v1
kind: Config
clusters:
  - name: authorize-service
    cluster:
      # this CA should be mounted on the api_server
      certificate-authority: /files/ca.crt
      # Replace this with authorizer address and endpoint
      server: https://192.168.8.5:8443/v0/authorize

users:
  - name: authorize-api-server
    user:
      # This will come in the request header(Authorization) of above URL.
      # Can be used to validate if the request is coming from configured cluster
      token: test-token

current-context: webhook
contexts:
- context:
    cluster: authorize-service
    user: authorize-api-server
  name: webhook