kind: ClusterReferenceGrant
apiVersion: reference.authorization.k8s.io/v1alpha1
metadata:
  name: gateways
from:
  group: gateway.networking.k8s.io
  resource: gateways
versions:
  - version: v1
    references:
      - path: "$.spec.listeners[*].tls.certificateRefs[*]"
        to:
          group: ""
          resource: secrets
        for: tls-serving
      - path: "$.spec.listeners[*].tls.certificateRefs[*]"
        to:
          group: ""
          resource: secrets
        for: ""

---
kind: ClusterReferenceConsumer
apiVersion: reference.authorization.k8s.io/v1alpha1
metadata:
  name: kong-gateway
subject:
  kind: ServiceAccount
  name: kong-controller
  namespace: kong
references:
  - from:
      group: gateway.networking.k8s.io
      resource: gateways
    to:
      group: ""
      resource: secrets
    for: ""
  - from:
      group: gateway.networking.k8s.io
      resource: gateways
    to:
      group: ""
      resource: secrets
    for: tls-serving

---
kind: ReferenceGrant
apiVersion: reference.authorization.k8s.io/v1alpha1
metadata:
  name: demo-gateways
  namespace: default
from:
  group: gateway.networking.k8s.io
  resource: gateways
  namespace: kong
to:
  group: ""
  resource: secrets
  names:
  - demo-tls-validity-checks-certificate
for: tls-serving