kind: ClusterReferenceConsumer
apiVersion: reference.authorization.k8s.io/v1alpha1
metadata:
  name: demo-controller-secrets
subject:
  kind: ServiceAccount
  name: demo-controller
  namespace: demo
references:
  - from:
      group: gateway.networking.k8s.io
      resource: gateways
    to:
      group: ""
      resource: secrets
    for: tls-serving
