# Kind cluster config for regular authz (non structured authz)
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        authorization-mode: "Webhook,Node,RBAC"
        authorization-webhook-version: "v1"
        authorization-webhook-config-file: "/files/authorize-webhook-conf.yaml"
        authorization-webhook-cache-authorized-ttl: "5s"
        authorization-webhook-cache-unauthorized-ttl: "5s"
      extraVolumes:
      - name: api-server-basic-auth-files
        hostPath: "/files"
        mountPath: "/files"
        readOnly: true
nodes:
- role: control-plane
  # Make sure you set the correct hostPath
  extraMounts:
  - hostPath: <referencegrant-poc-repo-path>/demo/files
    containerPath: /files